<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Yesh" failures="7" tests="8" name="Test" time="18.416" errors="0" timestamp="2025-04-16T20:53:24 IST">
  <testcase classname="api.test.Usertests" name="testPostUser" time="5.673"/>
  <testcase classname="api.test.Usertests" name="testGetUserByName" time="1.441">
    <failure type="java.lang.AssertionError" message="User retrieval failed! expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: User retrieval failed! expected [200] but found [404]
at api.test.Usertests.testGetUserByName(Usertests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.Usertests" name="testupdateUserbyName" time="3.123">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.Usertests.testupdateUserbyName(Usertests.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testupdateUserbyName -->
  <testcase classname="api.test.Usertests" name="testDeleteByName" time="1.378">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.Usertests.testDeleteByName(Usertests.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteByName -->
  <testcase classname="api.test.datadriventest" name="testPostUsers" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at api.utilities.DataProviderclass.getAllData(DataProviderclass.java:21)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testPostUsers -->
  <testcase classname="api.test.datadriventest" name="testdeleteusers" time="1.62">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.datadriventest.testdeleteusers(datadriventest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteusers -->
  <testcase classname="api.test.datadriventest" name="testdeleteusers" time="1.537">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.datadriventest.testdeleteusers(datadriventest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteusers -->
  <testcase classname="api.test.datadriventest" name="testdeleteusers" time="1.522">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.datadriventest.testdeleteusers(datadriventest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteusers -->
</testsuite> <!-- Test -->
